/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ClaimedRewardService } from "../claimedReward.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ClaimedRewardCreateInput } from "./ClaimedRewardCreateInput";
import { ClaimedRewardWhereInput } from "./ClaimedRewardWhereInput";
import { ClaimedRewardWhereUniqueInput } from "./ClaimedRewardWhereUniqueInput";
import { ClaimedRewardFindManyArgs } from "./ClaimedRewardFindManyArgs";
import { ClaimedRewardUpdateInput } from "./ClaimedRewardUpdateInput";
import { ClaimedReward } from "./ClaimedReward";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ClaimedRewardControllerBase {
  constructor(
    protected readonly service: ClaimedRewardService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ClaimedReward })
  @nestAccessControl.UseRoles({
    resource: "ClaimedReward",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: ClaimedRewardCreateInput
  ): Promise<ClaimedReward> {
    return await this.service.create({
      data: {
        ...data,

        reward: data.reward
          ? {
              connect: data.reward,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        qrCodeUrl: true,

        reward: {
          select: {
            id: true,
          },
        },

        rewardId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ClaimedReward] })
  @ApiNestedQuery(ClaimedRewardFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ClaimedReward",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<ClaimedReward[]> {
    const args = plainToClass(ClaimedRewardFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        qrCodeUrl: true,

        reward: {
          select: {
            id: true,
          },
        },

        rewardId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ClaimedReward })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClaimedReward",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: ClaimedRewardWhereUniqueInput
  ): Promise<ClaimedReward | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        qrCodeUrl: true,

        reward: {
          select: {
            id: true,
          },
        },

        rewardId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        userId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ClaimedReward })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClaimedReward",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: ClaimedRewardWhereUniqueInput,
    @common.Body() data: ClaimedRewardUpdateInput
  ): Promise<ClaimedReward | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          reward: data.reward
            ? {
                connect: data.reward,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          qrCodeUrl: true,

          reward: {
            select: {
              id: true,
            },
          },

          rewardId: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ClaimedReward })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClaimedReward",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: ClaimedRewardWhereUniqueInput
  ): Promise<ClaimedReward | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          qrCodeUrl: true,

          reward: {
            select: {
              id: true,
            },
          },

          rewardId: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
