/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Reward,
  ClaimedReward,
  FavouriteReward,
  Organisation,
  RewardImage,
} from "@prisma/client";

export class RewardServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.RewardFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.RewardFindManyArgs>
  ): Promise<number> {
    return this.prisma.reward.count(args);
  }

  async findMany<T extends Prisma.RewardFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.RewardFindManyArgs>
  ): Promise<Reward[]> {
    return this.prisma.reward.findMany(args);
  }
  async findOne<T extends Prisma.RewardFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.RewardFindUniqueArgs>
  ): Promise<Reward | null> {
    return this.prisma.reward.findUnique(args);
  }
  async create<T extends Prisma.RewardCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.RewardCreateArgs>
  ): Promise<Reward> {
    return this.prisma.reward.create<T>(args);
  }
  async update<T extends Prisma.RewardUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.RewardUpdateArgs>
  ): Promise<Reward> {
    return this.prisma.reward.update<T>(args);
  }
  async delete<T extends Prisma.RewardDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.RewardDeleteArgs>
  ): Promise<Reward> {
    return this.prisma.reward.delete(args);
  }

  async findClaimedRewards(
    parentId: string,
    args: Prisma.ClaimedRewardFindManyArgs
  ): Promise<ClaimedReward[]> {
    return this.prisma.reward
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .claimedRewards(args);
  }

  async findFavouriteRewards(
    parentId: string,
    args: Prisma.FavouriteRewardFindManyArgs
  ): Promise<FavouriteReward[]> {
    return this.prisma.reward
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .favouriteRewards(args);
  }

  async getOrganisation(parentId: string): Promise<Organisation | null> {
    return this.prisma.reward
      .findUnique({
        where: { id: parentId },
      })
      .organisation();
  }

  async getRewardImage(parentId: string): Promise<RewardImage | null> {
    return this.prisma.reward
      .findUnique({
        where: { id: parentId },
      })
      .rewardImage();
  }
}
