/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RewardService } from "../reward.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RewardCreateInput } from "./RewardCreateInput";
import { RewardWhereInput } from "./RewardWhereInput";
import { RewardWhereUniqueInput } from "./RewardWhereUniqueInput";
import { RewardFindManyArgs } from "./RewardFindManyArgs";
import { RewardUpdateInput } from "./RewardUpdateInput";
import { Reward } from "./Reward";
import { ClaimedRewardFindManyArgs } from "../../claimedReward/base/ClaimedRewardFindManyArgs";
import { ClaimedReward } from "../../claimedReward/base/ClaimedReward";
import { ClaimedRewardWhereUniqueInput } from "../../claimedReward/base/ClaimedRewardWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RewardControllerBase {
  constructor(
    protected readonly service: RewardService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Reward })
  @nestAccessControl.UseRoles({
    resource: "Reward",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: RewardCreateInput): Promise<Reward> {
    return await this.service.create({
      data: {
        ...data,

        organisation: data.organisation
          ? {
              connect: data.organisation,
            }
          : undefined,

        rewardImage: data.rewardImage
          ? {
              connect: data.rewardImage,
            }
          : undefined,
      },
      select: {
        city: true,
        country: true,
        createdAt: true,
        description: true,
        discount: true,
        expirationDate: true,
        id: true,
        latitude: true,
        longitude: true,
        miles: true,

        organisation: {
          select: {
            id: true,
          },
        },

        rewardImage: {
          select: {
            id: true,
          },
        },

        title: true,
        totalCount: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Reward] })
  @ApiNestedQuery(RewardFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Reward",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Reward[]> {
    const args = plainToClass(RewardFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        city: true,
        country: true,
        createdAt: true,
        description: true,
        discount: true,
        expirationDate: true,
        id: true,
        latitude: true,
        longitude: true,
        miles: true,

        organisation: {
          select: {
            id: true,
          },
        },

        rewardImage: {
          select: {
            id: true,
          },
        },

        title: true,
        totalCount: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Reward })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reward",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: RewardWhereUniqueInput
  ): Promise<Reward | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        city: true,
        country: true,
        createdAt: true,
        description: true,
        discount: true,
        expirationDate: true,
        id: true,
        latitude: true,
        longitude: true,
        miles: true,

        organisation: {
          select: {
            id: true,
          },
        },

        rewardImage: {
          select: {
            id: true,
          },
        },

        title: true,
        totalCount: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Reward })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reward",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: RewardWhereUniqueInput,
    @common.Body() data: RewardUpdateInput
  ): Promise<Reward | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          organisation: data.organisation
            ? {
                connect: data.organisation,
              }
            : undefined,

          rewardImage: data.rewardImage
            ? {
                connect: data.rewardImage,
              }
            : undefined,
        },
        select: {
          city: true,
          country: true,
          createdAt: true,
          description: true,
          discount: true,
          expirationDate: true,
          id: true,
          latitude: true,
          longitude: true,
          miles: true,

          organisation: {
            select: {
              id: true,
            },
          },

          rewardImage: {
            select: {
              id: true,
            },
          },

          title: true,
          totalCount: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Reward })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reward",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: RewardWhereUniqueInput
  ): Promise<Reward | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          city: true,
          country: true,
          createdAt: true,
          description: true,
          discount: true,
          expirationDate: true,
          id: true,
          latitude: true,
          longitude: true,
          miles: true,

          organisation: {
            select: {
              id: true,
            },
          },

          rewardImage: {
            select: {
              id: true,
            },
          },

          title: true,
          totalCount: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/claimedRewards")
  @ApiNestedQuery(ClaimedRewardFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ClaimedReward",
    action: "read",
    possession: "any",
  })
  async findManyClaimedRewards(
    @common.Req() request: Request,
    @common.Param() params: RewardWhereUniqueInput
  ): Promise<ClaimedReward[]> {
    const query = plainToClass(ClaimedRewardFindManyArgs, request.query);
    const results = await this.service.findClaimedRewards(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        qrCodeUrl: true,

        reward: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/claimedRewards")
  @nestAccessControl.UseRoles({
    resource: "Reward",
    action: "update",
    possession: "any",
  })
  async connectClaimedRewards(
    @common.Param() params: RewardWhereUniqueInput,
    @common.Body() body: ClaimedRewardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      claimedRewards: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/claimedRewards")
  @nestAccessControl.UseRoles({
    resource: "Reward",
    action: "update",
    possession: "any",
  })
  async updateClaimedRewards(
    @common.Param() params: RewardWhereUniqueInput,
    @common.Body() body: ClaimedRewardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      claimedRewards: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/claimedRewards")
  @nestAccessControl.UseRoles({
    resource: "Reward",
    action: "update",
    possession: "any",
  })
  async disconnectClaimedRewards(
    @common.Param() params: RewardWhereUniqueInput,
    @common.Body() body: ClaimedRewardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      claimedRewards: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
