/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ClaimedRewardCreateNestedManyWithoutUsersInput } from "./ClaimedRewardCreateNestedManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString, IsJSON } from "class-validator";
import { Type } from "class-transformer";
import { CompanyDetailCreateNestedManyWithoutUsersInput } from "./CompanyDetailCreateNestedManyWithoutUsersInput";
import { FavouriteRewardCreateNestedManyWithoutUsersInput } from "./FavouriteRewardCreateNestedManyWithoutUsersInput";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => ClaimedRewardCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ClaimedRewardCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ClaimedRewardCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  claimedRewards?: ClaimedRewardCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CompanyDetailCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CompanyDetailCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CompanyDetailCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  companyDetails?: CompanyDetailCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => FavouriteRewardCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => FavouriteRewardCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => FavouriteRewardCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  favouriteRewards?: FavouriteRewardCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSON()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
