/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FavouriteRewardService } from "../favouriteReward.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FavouriteRewardCreateInput } from "./FavouriteRewardCreateInput";
import { FavouriteRewardWhereInput } from "./FavouriteRewardWhereInput";
import { FavouriteRewardWhereUniqueInput } from "./FavouriteRewardWhereUniqueInput";
import { FavouriteRewardFindManyArgs } from "./FavouriteRewardFindManyArgs";
import { FavouriteRewardUpdateInput } from "./FavouriteRewardUpdateInput";
import { FavouriteReward } from "./FavouriteReward";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FavouriteRewardControllerBase {
  constructor(
    protected readonly service: FavouriteRewardService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FavouriteReward })
  @nestAccessControl.UseRoles({
    resource: "FavouriteReward",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: FavouriteRewardCreateInput
  ): Promise<FavouriteReward> {
    return await this.service.create({
      data: {
        ...data,

        reward: data.reward
          ? {
              connect: data.reward,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        reward: {
          select: {
            id: true,
          },
        },

        rewardId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FavouriteReward] })
  @ApiNestedQuery(FavouriteRewardFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FavouriteReward",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<FavouriteReward[]> {
    const args = plainToClass(FavouriteRewardFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,

        reward: {
          select: {
            id: true,
          },
        },

        rewardId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FavouriteReward })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FavouriteReward",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: FavouriteRewardWhereUniqueInput
  ): Promise<FavouriteReward | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,

        reward: {
          select: {
            id: true,
          },
        },

        rewardId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        userId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FavouriteReward })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FavouriteReward",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: FavouriteRewardWhereUniqueInput,
    @common.Body() data: FavouriteRewardUpdateInput
  ): Promise<FavouriteReward | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          reward: data.reward
            ? {
                connect: data.reward,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          reward: {
            select: {
              id: true,
            },
          },

          rewardId: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FavouriteReward })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FavouriteReward",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: FavouriteRewardWhereUniqueInput
  ): Promise<FavouriteReward | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,

          reward: {
            select: {
              id: true,
            },
          },

          rewardId: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
